FROM mysql:8.0

# Variables de entorno para crear la base de datos automáticamente
ENV MYSQL_ROOT_PASSWORD=rootpass
ENV MYSQL_DATABASE=tasks_db
ENV MYSQL_USER=roelcode
ENV MYSQL_PASSWORD=123456

# Puerto por defecto de MySQL
EXPOSE 3306
